### ISSUE TITLE
Add one more Delta DTA

### ISSUE THREAD

**Issue by Appletone** [MAKOMO/artisan#80]
Is it possible add third DTA by setting?

**Comment by MAKOMO** [comment]
No, that would break the 2-channels per device structure of Artisan. However, it is possible to add an extra MODBUS device, specify the correct device id and register to be read from in the MODBUS tab. By default those MODBUS extra devices assume to be on an extra physical MODBUS ring connected to the port specified in that MODBUS tab. However, if the flag "MODBUS port" in the ET/BT tab of the Device Assignment dialog is ticked, the selected PIDs use the same MODBUS port specified in the MODBUS tab and not that one specified in under serial settings. That way you can read in from an unlimited number of MODBUS devices/channels. However, the extra PID dialogs are only supporting the main PID devices.
